### ISSUE TITLE
Full Schema for app-events

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#173]
## Full Schema
- [x] All tables are built out for the event ERD
- [x] Test data made for all tables in event ERD
- [x] All storycards connected to this Story are complete (All API integration complete)

### Tables Checklist
- [x] event
   - [x] test data written for event
- [x] event_participant
   - [x] test data written for event_participant
- [x] event_asset
   - [x] test data written for event_asset
- [x] event_team
   - [x] test data written for event_team
- [x] event_person
   - [x] test data written for event_person
- [x] asset
   - [x] test data written for asset
- [x] team
   - [x] test data written for team
- [x] team_member
   - [x] test data written for team_member
