### ISSUE TITLE
Groups - Meeting Attendance Tracking

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#333]
Complete story first: #384 --> set up meetings page and functionality
## Attendance tracking must be mobile-friendly
Build out the necessary functionality to implement group attendance tracking.

A group leader (or higher permission) can track the attendance of members to its homegroup.  The system can display this tracking data in a meaningful way on a page (preferably a dashboard)

- [ ] On the meetings tab of groups, there should be a button representing taking attendance under the actions section.
- [ ] Once the `take attendance` button is clicked, there should be a pop-up that is a scrollable list of all active members with checkboxes next to their names.
- [ ] Once the manager is satisfied with taking attendance, there needs to be a `save` button.
- [ ] If the manager accidentally hits the take attendance button, there should be a `cancel` button.

**Comment by quiteqiang** [comment]
All the requirements should be satisfied by the current meeting features
