### ISSUE TITLE
Utilities to maintain translation entries

### ISSUE THREAD

**Issue by PROgram52bc** [corpus-christi/corpus-christi#582]
The following are potential utilities/features that we might want in the future, after migrating the yaml files into the database:

User interface
- [x] A user interface to list all keys with their corresponding translations in a tree-based structure, that would let the translator “zoom in” on a particular group of strings and add, change, or delete translation entries. Each entry also has a "verified" flag, indicating whether the translation has been verified by a native speaker. This flag is editable through the tree structure.
- [x] Changes made through the user interface will go directly into the database (admins can then use the command-line utility to export the database to a JSON file in order to keep the translation entries in the revision control).
- [x] Have a global switch for the "translator" to turn off all translation and display the raw string, in order to identify the key of a certain text that appeared in the application.

Command line utility
- [x] A command line utility to export the database entries into a json file/import a json file into the database (e.g. `flask i18n dump <locale> [--target i18n/{locale}.json]`). Then developers can use this to diff the changes made to the translation, and commit to the revision control.

- [x] `flask i18n import/export [--target file.yaml] [the.key.path]` command to dump in `locale-tail` structure, yaml format.
   - [x] use a implementation function to achieve the result.
   - [x] `flask i18n list [the.key.path]`, alias for `flask i18n export --target -`.
   - [x] `flask i18n update --locale <locale> [the.key.path] [value]`, alias for `flask i18n import --target - --override <<< "<locale>: [value]"`
      - except first check whether [the.key.path] is an actual key
   - [x] `flask i18n add --locale <locale> [the.key.path] [value]`, alias for `flask i18n import --target - --no-override <<< "<locale>: [value]"`
   - [x] `flask i18n edit [the.key.path]`, same thing as 
      1. `flask i18n export --target random.yaml [the.key.path]`
      1. open random.yaml with the preferred editor
      1. upon save, run `flask i18n import --target random.yaml [the.key.path]`
      1. delete random.yaml
      > Use [click.edit](https://click.palletsprojects.com/en/7.x/utils/?highlight=editor#launching-editors)
   - [x] For `import`, provide `--override` flag that overrides existing entries. But like `load`, never delete entries that are not in the given file, also the `verified` flag will be set to false when entries are updated.
- [x] A command line utility to delete individual items (e.g. `flask language delete --locale en-US [the.key.path]`)
   - For `delete`, can specify a `-r` flag to delete entries starting with a given path.
   - When `locale` is "all", delete the given entries with all locales.
- [x] A command line utility to complete translations using machine translation (e.g. `flask language translate [--delay 0.3] [-i/--interactive] [src_locale] [dest_locale]`).
   - [x] should list all possible `src_locale` and `dest_locale` in `--help`

Documentation:
- [x] explain the difference between dump and export command
- [x] explain the "locale-tail" structure
   >  a "locale-tail" tree is a tree where each end entry contains its corresponding gloss in different locales, as opposed to a "locale-head" tree, where entry gloss themselves are categorized according to the locales.
- [x] a brief overview of all available commands
- [x] explain some common options (e.g. `--target`)
- [ ] ~describe some common workflow~
   - how to initialize the database with languages
   - how to add new keys interactively
   - after adding new keys, how to auto-internationalize it into multiple languages
   - how to track new entries with revision control.
- [x] capitalize help messages, add short-help for commands that have long help messages.
- [x] add example usage in commands
   - [x] delete
   - [x] dump

Enhancement:
- [ ] ~A command line utility to list unused translation entries, with the option to remove them.~
   - ~It can be hard to identify unused entries, if we are only using text-based utilities like `grep`, since it will miss computed keys (e.g. `` `${ condition ? "this" : "that" }.item` ``)~

**Comment by PROgram52bc** [comment]
change the validator for `I18NKeySchema.id` in `src/i18n/models.py` to allow dashes in key?

**Comment by PROgram52bc** [comment]
## Milestone 1:

- [x] convert current yaml files into a single json file that persists all information (including the `_desc`, and a `verified` flag for each entry, but not comments)
- [x] utility to import from/export to the json file to/from the database. (json <==> database)

## Milestone 2:

- [x] configure UI to fetch translation entries from the database via the `/i18n/values/<locale>?format=tree` endpoint
- [x] API
   - [x] update endpoint to update entry of a certain locale (`def update_xlation(locale_code)` with a path `values/<locale>` and a payload `{ gloss?, verified?, key }
   - [x] tests for the endpoint
   

## Milestone 3:

- [x] migrate the `complete_translation` script into a flask command
- [x] implement a command to list entries from database
