### ISSUE TITLE
Events/Calendar_View

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#76]
## Events Calendar View - UI and QA
branch to merge changes => app-events-events-calendarview
### Functionality Checklist
- [x] 1. Show Event's in a calendar view; (UI team)
	* allow the same date ranges as for the list view.
- [x] 2. API integration complete (UI team + API)
- [ ] 3. End-to-end testing for this UI functionality (QA & UI teams)

**Comment by Noahffiliation** [comment]
Routing issue on the calendar
