### ISSUE TITLE
Assets/CRUD

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#89]
### Functionality Checklist
- [ ] 1.  Add a new Asset. Allow the location to be set using the same criteria as for creating an Event.
- [ ] 2. Update the details for an Asset.
- [ ] 3. Deactivate or reactivate an Asset (an inactive Asset is no longer available for future Event's)
